### ISSUE TITLE
Update Notes

### ISSUE THREAD

**Issue by RoelBrandenburg** [RUGSoftEng/2018-Tuberculosis#89]
The idea is that a patient can review the questions asked to the physician and can update or remove those questions. 

Is it possible to have a POST and REMOVE API call for the notes?

**Comment by RoelBrandenburg** [comment]
Can the DELETE and POST method also be added to the API documentation?

Also to be able to DELETE or POST the right note we need to know its ID, maybe it is a good idea that the ID of a note is stored in the note (then we know its ID when we use the GET method).

**Comment by StenSipma** [comment]
Okay the requests have already been made. One of them does return the Id I will look intoit further tomorrow.

**Comment by StenSipma** [comment]
#97 Requests are now correct and documented. Only has to be merged and server has to be updated for it to work.

**Comment by RoelBrandenburg** [comment]
Great, Thanks!
